"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:lotus_violet_3)\
$os\
$directory\
$git_branch\
$git_status\
$golang\
$lua\
$python\
$rust\
$fill\
$time\
$cmd_duration
[╰─$shlvl$character](fg:lotus_violet_3)"""

palette = 'kanagawa'

[character]
disabled = false
success_symbol = "[❯](lotus_violet_3)"
error_symbol = "[❯](wave_red)"
vimcmd_symbol = "[❮](oni_violet)"

[os]
disabled = false
style = "fg:lotus_violet_3"
format = '[$symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:lotus_violet_1"
style_root = "fg:lotus_red"
format = '[$user ]($style)'

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"dotfiles" = ""

[directory]
read_only = " "
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
style = "fg:lotus_green_3"
format = "[ $path ]($style)"

[git_branch]
symbol = " "
style = "fg:lotus_yellow_4"
format = '[on $symbol$branch ]($style)'

[git_status]
style = "fg:sakura_pink"
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = " "
style = "fg:lotus_aqua"
format = '[$symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:crystal_blue"
format = '[$symbol ($version) ]($style)'
version_format = "${raw}"

[python]
symbol = ""
style = "fg:crystal_blue"
format = '[$symbol ($version)(\($virtualenv\)) ]($style)'
version_format = "v${raw}"

[rust]
symbol = ""
style = "fg:lotus_orange"
format = '[$symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:lotus_gray_3"
format = '[  $time ]($style)'

[cmd_duration]
disabled = false
show_milliseconds = false
show_notifications = true
min_time_to_notify = 45000
min_time = 5000
style = "bold italic wave_red"
format = "[took $duration ]($style)"

[shlvl]
disabled = false
symbol = "󰨊"
style = "bold italic wave_red"
format = '[ $symbol─($shlvl) ]($style)'

[line_break]
disabled = true

[fill]
symbol = ' '

[palettes.kanagawa]
wave_red = "#E46876"
crystal_blue = "#7E9CD8"
sakura_pink = "#D27E99"
lotus_gray_3 = "#8a8980"
lotus_orange = "#cc6d00"
lotus_aqua = "597b75"
lotus_yellow_4 = "#f9d791"
lotus_green_3 = "#b7d0ae"
lotus_violet_1 = "#a09cac"
lotus_violet_3 = "#c9cbd1"
lotus_red = "#c84053"
oni_violet = "#957FB8"
