theme               = "gruvbox_dark_hard"


## insert-mode -----------------------------------
## <S-tab>          = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## <C-i>            = fetch signature help when needed, auto-signature-help is now disabled, this helps in avoiding the adamant signature hint popup
## <C-[>            = to come to normal, makes a lot of sense if you have replaced capslock with ctrl
## <C-f>            = macOS keybinding to move right in insert mode
## <C-b>            = macOS keybinding to move left in insert mode
## <C-n>            = macOS keybinding to move down in insert mode
## <C-p>            = macOS keybinding to move up in insert mode
## <disable>        = up / down / right / left / pageup / page down / home / end
# ------------------------------------------------
[keys.insert]
"S-tab"             = "move_parent_node_start"
"C-i"               = "signature_help"
"C-["               = "normal_mode"
"C-f"               = ["normal_mode", "move_char_right", "insert_mode"]
"C-b"               = ["normal_mode", "move_char_left",  "insert_mode"]
"C-n"               = ["normal_mode", "move_visual_line_down", "insert_mode"]
"C-p"               = ["normal_mode", "move_visual_line_up", "insert_mode"]
"up"                = "no_op"
"down"              = "no_op"
"left"              = "no_op"
"right"             = "no_op"
"pageup"            = "no_op"
"pagedown"          = "no_op"
"home"              = "no_op"
"end"               = "no_op"


## select-mode -----------------------------------
## <tab> & <S-tab>  = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## <~> / <A-`>      = to switch to uppercase / to switch case, reversed the default bahavior / kakoune's keybindings are more natural
## <ret>            = Alternative to <A-.>, easier to do
## <C-c>            = <<space>-c> does the job well, freeing the keybinding for a better use in future
# ------------------------------------------------
[keys.select]
"tab"               = "extend_parent_node_end"
"S-tab"             = "extend_parent_node_start"
"~"                 = "switch_to_uppercase"
"A-`"               = "switch_case"
"ret"               = "repeat_last_motion"
"C-c"               = "no_op"

## select-space-mode -----------------------------
## <u>              = to switch to lower case, available in normal mode as well.
## <U>              = to switch to upper case, available in normal mode as well.
# ------------------------------------------------
[keys.select.space]
"u"                 = "switch_to_lowercase"
"U"                 = "switch_to_uppercase"


## normal-mode -----------------------------------
## <tab> & <S-tab>  = use smart tab -> https://docs.helix-editor.com/editor.html#editorsmart-tab-section
## <C-c>            = <<space>-c> does the job well, freeing the keybinding for a better use in future
## <C-ret>          = insert new line and go into insert mode
## <x>              = will unselect the line(s) downwards if selected by previous (X) command, else will extend downwards
## <X>              = will unselect the line(s) upwards if selected by previous (x) command, else will extend upwards
## <~> / <A-`>      = to switch to uppercase / to switch case, reversed the default bahavior / kakoune's keybindings are more natural
## <ret>            = Alternative to <A-.>, easier to do
## <esc>            = also used to collapse selection
# ------------------------------------------------
[keys.normal]
"tab"               = "move_parent_node_end"
"S-tab"             = "move_parent_node_start"
"C-c"               = "no_op"
"C-ret"             = ["insert_newline", "insert_mode"]
"x"                 = "select_line_below"
"X"                 = "select_line_above"
"~"                 = "switch_to_uppercase"
"A-`"               = "switch_case"
"ret"               = "repeat_last_motion"
esc                 = ["collapse_selection"]

## normal-space-mode -----------------------------
## u                = to switch to lower case, available in select mode as well.
## U                = to switch to upper case, available in select mode as well.
## q                = to close the current buffer
## Q                = to force close the current buffer
## n                = to open a new vertical scratch buffer
## N                = to open a new horizontal scratch buffer
# ------------------------------------------------
[keys.normal.space]
"u"                 = "switch_to_lowercase"
"U"                 = "switch_to_uppercase"
"q"                 = ":buffer-close"
"Q"                 = ":buffer-close!"
"n"                 = ":vsplit-new"
"N"                 = ":hsplit-new"

## normal-<C-g>-mode [git commands]---------------
## <s>              = git status
## <l>              = git log
## <a>              = git add <file>
# ------------------------------------------------
[keys.normal."C-g"]
"s"                 = ["align_view_top", ":sh git status"]
"l"                 = ["align_view_top", ":sh git log"]
"a"                 = "@:sh git add <C-r>%<ret>"

[editor]
scrolloff           = 2
insert-final-newline = true
cursorline          = true
cursorcolumn        = true
line-number         = "relative"
mouse               = true
bufferline          = "always"
color-modes         = true
completion-timeout  = 5 ## instantly render completions
popup-border        = "all" ## make popups look a bit tidy
end-of-line-diagnostics = "disable"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.cursor-shape]
insert              = "bar" ## visually distinguish between insert / normal mode

[editor.auto-pairs]
'('                 = ')'
'{'                 = '}'
'['                 = ']'
'"'                 = '"'
'`'                 = '`'
"'"                 = "'"

[editor.indent-guides]
render              = true
character           = "▏"  ## Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels         = 1

[editor.soft-wrap]
enable              = false

[editor.statusline]
mode.normal         = "NORMAL"
mode.insert         = "INSERT"
mode.select         = "SELECT"
left                = ["mode", "file-base-name", "file-modification-indicator", "read-only-indicator"]
center              = ["spinner", "file-name", "total-line-numbers", "separator", "position", "separator", "position-percentage", "spacer", "separator", "version-control"]
right               = ["file-encoding", "diagnostics", "separator", "selections", "separator", "file-line-ending", "separator", "file-type"]
separator           = "▏"

## ref:
##   https://github.com/helix-editor/helix/pull/1570
##   https://www.reddit.com/r/HelixEditor/comments/11alw7q/delete_to_end_of_line/
##   https://github.com/helix-editor/helix/issues/1630
##   https://www.reddit.com/r/HelixEditor/comments/yqfei5/toggle_signature_help/
